### Создать задачу №1 (POST принимает одиночный объект, а не массив)
POST http://localhost:5182/tasks
Content-Type: application/json

{
    "Title" : "1234",
    "IsCompleted" : false
}

### Создать задачу №2
POST http://localhost:5182/tasks
Content-Type: application/json

{
    "Title" : "Задача 2",
    "IsCompleted" : true
}

###
GET http://localhost:5182/tasks/whoami
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4iLCJleHAiOjE3ODQ5MDQzMTAsImlzcyI6IlRhc2tGbG93QVBJIiwiYXVkIjoiVGFza0Zsb3dDbGllbnRzIn0.DJoazwg0hB1rDdAFt3bFAnXhzBlGMg4mwnnzj9j5k9c

### Получить все задачи (фильтер)
GET http://localhost:5182/tasks/filter
### Получить все задачи (фильтер IsCompleted=true)
GET http://localhost:5182/tasks/filter?isCompleted=true
### Получить все задачи (фильтер IsCompleted=false)
GET http://localhost:5182/tasks/filter?isCompleted=false

### Получить все задачи без токена
GET http://localhost:5182/tasks

### Получить все задачи с токеном токена
GET http://localhost:5182/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4iLCJleHAiOjE3ODQ5MDQzMTAsImlzcyI6IlRhc2tGbG93QVBJIiwiYXVkIjoiVGFza0Zsb3dDbGllbnRzIn0.DJoazwg0hB1rDdAFt3bFAnXhzBlGMg4mwnnzj9j5k9c

### Получить токен
POST http://localhost:5182/auth/login
Content-Type: application/json

{
    "Login" : "admin",
    "Password" : "password"
}

### Получить конкретную задачу по ID
GET http://localhost:5182/tasks/1
### Тест GET
GET http://localhost:5182/tasks/2315

### Обновить задачу (Параметр ID передается в URL, а измененные данные — в теле)
PUT http://localhost:5182/tasks/1
Content-Type: application/json

{
    "Title" : "Обновленная задача 1",
    "IsCompleted" : true
}

### Удалить задачу (Параметр ID передается в URL)
DELETE http://localhost:5182/tasks/2
